### ISSUE TITLE
download-libssl-dev.sh run error on mac

### ISSUE THREAD

**Issue by kael777** [chinedufn/cross-compile-rust-from-mac-to-linux#1]
ar: libssl-dev_1.1.1h-1_amd64.deb: Inappropriate file type or format

**Comment by chinedufn** [comment]
Looks like the download link is 404'ing


`curl http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl-dev_1.1.1h-1_amd64.deb`

produces:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /debian/pool/main/o/openssl/libssl-dev_1.1.1h-1_amd64.deb was not found on this server.</p>
<hr>
<address>Apache Server at ftp.us.debian.org Port 80</address>
</body></html>

```

**Comment by chinedufn** [comment]
If you're looking for a quick fix you can just find a different libssl-dev download link that doesn't 404 and use that.

Let me know if that works for you!

**Comment by kael777** [comment]
thanks ,I found a download link and it works for me now

**Comment by chinedufn** [comment]
Awesome! Mind passing me that link so that I can update the codebase?

**Comment by kael777** [comment]
> Awesome! Mind passing me that link so that I can update the codebase?

Hi,I download a different version "1.1.1i-2" from debian.org,the link is
http://ftp.br.debian.org/debian/pool/main/o/openssl/libssl-dev_1.1.1i-2_arm64.deb

**Comment by chinedufn** [comment]
Thanks!
